#  pylint: disable=missing-docstring
from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'big_icon.ico'

# Sizing
BIG_FONT_SIZE = 30
MEDIUM_FONT_SIZE = 20
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 10
MINIMUM_WIDTH = 400

# Colors
PRIMARY_COLOR = '#ED3237'
DARKER_PRIMARY_COLOR = '#BF2424'
DARKEST_PRIMARY_COLOR = '#8E1715'

# Especial Colors
ESPECIAL_PRIMARY_COLOR = '#222226'
ESPECIAL_DARKER_PRIMARY_COLOR = '#ED3237'
ESPECIAL_DARKEST_PRIMARY_COLOR = '#8E1715'
